POST http://localhost:8080/api/auth/sign_up
Content-Type: application/json

{
    "email": "teacher@gmail.com",
    "password": "qwerty",
    "role": "teacher"
}

> {% client.global.set("user_id", response.body.id); %}

###

DELETE http://localhost:8080/api/auth/sign_out

###

POST http://localhost:8080/api/auth/sign_in
Content-Type: application/json

{
  "email": "teacher@gmail.com",
  "password": "qwerty"
}

