### teacher sign up

POST http://localhost:8080/api/v1/auth/sign_up
Content-Type: application/json

{
  "email": "teacher100@gmail.com",
  "password": "qwerty",
  "role": "teacher"
}


> {% client.global.set("cookie", response.headers.valueOf('Set-Cookie')); %}

### teacher check session

GET http://localhost:8080/api/v1/auth/check_session
Accept: application/json
Cookie: {{cookie}}

### teacher sign out

DELETE http://localhost:8080/api/v1/auth/sign_out
Accept: application/json
Cookie: {{cookie}}

### teacher sign in

POST http://localhost:8080/api/v1/auth/sign_in
Content-Type: application/json

{
  "email": "teacher100@gmail.com",
  "password": "qwerty"
}
> {% client.global.set("cookie", response.headers.valueOf('Set-Cookie')); %}
